# docker-compose.yml

version: '3.9'

services:

  elastic:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    ports:
      - 9200:9200 
      - 9300:9300
    restart: always
    environment: 
      discovery.type: "single-node"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.18
    ports: 
      - 5601:5601
    restart: always
    depends_on:
      - elastic


networks:
  default:
    name: cicada_local_network