USE [master]
GO

/****** Object:  Database [LiberPrimus]    Script Date: 3/4/2024 8:18:50 PM ******/
DROP DATABASE [LiberPrimus]
GO

/****** Object:  Database [LiberPrimus]    Script Date: 3/4/2024 8:18:50 PM ******/
CREATE DATABASE [LiberPrimus]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LiberPrimus', FILENAME = N'/var/opt/mssql/data/LiberPrimus.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LiberPrimus_log', FILENAME = N'/var/opt/mssql/data/LiberPrimus_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LiberPrimus].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LiberPrimus] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LiberPrimus] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LiberPrimus] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LiberPrimus] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LiberPrimus] SET ARITHABORT OFF 
GO

ALTER DATABASE [LiberPrimus] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LiberPrimus] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LiberPrimus] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LiberPrimus] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LiberPrimus] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LiberPrimus] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LiberPrimus] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LiberPrimus] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LiberPrimus] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LiberPrimus] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LiberPrimus] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LiberPrimus] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LiberPrimus] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LiberPrimus] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LiberPrimus] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LiberPrimus] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LiberPrimus] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LiberPrimus] SET RECOVERY FULL 
GO

ALTER DATABASE [LiberPrimus] SET  MULTI_USER 
GO

ALTER DATABASE [LiberPrimus] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LiberPrimus] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LiberPrimus] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LiberPrimus] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LiberPrimus] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LiberPrimus] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LiberPrimus] SET QUERY_STORE = ON
GO

ALTER DATABASE [LiberPrimus] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [LiberPrimus] SET  READ_WRITE 
GO

USE [LiberPrimus]
GO

/****** Object:  Table [dbo].[COLOR_TOTIENT_SET]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COLOR_TOTIENT_SET](
	[COLOR_TOTIENT_SET_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TOTIENT_NUMBER] [bigint] NOT NULL,
	[LIBER_COLOR_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_COLOR_TOTIENT_SET] PRIMARY KEY CLUSTERED 
(
	[COLOR_TOTIENT_SET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[LIBER_COLOR]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LIBER_COLOR](
	[LIBER_COLOR_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LIBER_PAGE_ID] [int] NOT NULL,
	[PIX_COLOR_ID] [bigint] NOT NULL,
	[LINE_ORIENTATION_ID] [int] NOT NULL,
	[COLOR_COUNT] [bigint] NOT NULL,
	[IS_PRIME] [bit] NOT NULL,
	[GEMETRIA_VALUE] [nvarchar](5) NULL,
	[PHI_VALUE] [bigint] NULL,
	[CHARACTER_VALUE] [nvarchar](5) NULL,
 CONSTRAINT [PK_LIBER_COLOR] PRIMARY KEY CLUSTERED 
(
	[LIBER_COLOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[LIBER_PAGE]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LIBER_PAGE](
	[LIBER_PAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[LIBER_PAGE_NAME] [nvarchar](50) NOT NULL,
	[LIBER_PAGE_SIG] [nvarchar](255) NOT NULL,
	[LIBER_PAGE_TOTAL_COLORS] [int] NOT NULL,
	[LIBER_PAGE_HEIGHT] [int] NOT NULL,
	[LIBER_PAGE_WIDTH] [int] NOT NULL,
 CONSTRAINT [PK_LIBER_PAGE] PRIMARY KEY CLUSTERED 
(
	[LIBER_PAGE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[LINE_COLOR_INFO]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LINE_COLOR_INFO](
	[LINE_COLOR_INFO_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[LINE_NUMBER] [bigint] NOT NULL,
	[PIX_COLOR_ID] [bigint] NOT NULL,
	[LIBER_PAGE_ID] [int] NOT NULL,
	[LINE_ORIENTATION_ID] [int] NOT NULL,
	[LINE_COLOR_COUNT] [int] NOT NULL,
	[IS_PRIME] [bit] NOT NULL,
	[GEMETRIA_VALUE] [nvarchar](5) NULL,
	[PHI_VALUE] [bigint] NULL,
	[CHARACTER_VALUE] [nvarchar](5) NULL,
 CONSTRAINT [PK_LINE_COLOR_INFO] PRIMARY KEY CLUSTERED 
(
	[LINE_COLOR_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[LINE_ORIENTATION]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LINE_ORIENTATION](
	[LINE_ORIENTATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[LINE_ORIENTATION_NAME] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LINE_ORIENTATION] PRIMARY KEY CLUSTERED 
(
	[LINE_ORIENTATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PIX_COLOR]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PIX_COLOR](
	[PIX_COLOR_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PIX_COLOR_VALUE] [nvarchar](10) NULL,
 CONSTRAINT [PK_PIX_COLOR] PRIMARY KEY CLUSTERED 
(
	[PIX_COLOR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[PIXEL_POSITION_INFO]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PIXEL_POSITION_INFO](
	[PIXEL_POSITION_INFO_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PIXEL_POSITION_X] [bigint] NOT NULL,
	[PIXEL_POSITION_Y] [bigint] NOT NULL,
	[PIXEL_POSITION_CHANNELS] [int] NOT NULL,
	[PIX_COLOR_ID] [bigint] NOT NULL,
	[LIBER_PAGE_ID] [int] NOT NULL,
 CONSTRAINT [PK_PIXEL_POSITION_INFO] PRIMARY KEY CLUSTERED 
(
	[PIXEL_POSITION_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TOTIENT_SET]    Script Date: 3/4/2024 8:21:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TOTIENT_SET](
	[TOTIENT_SET_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TOTIENT_NUMBER] [bigint] NOT NULL,
	[LINE_COLOR_INFO_ID] [bigint] NOT NULL,
 CONSTRAINT [PK_TOTIENT_SET] PRIMARY KEY CLUSTERED 
(
	[TOTIENT_SET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COLOR_TOTIENT_SET]  WITH CHECK ADD  CONSTRAINT [FK_COLOR_TOTIENT_SET_LIBER_COLOR] FOREIGN KEY([LIBER_COLOR_ID])
REFERENCES [dbo].[LIBER_COLOR] ([LIBER_COLOR_ID])
GO

ALTER TABLE [dbo].[COLOR_TOTIENT_SET] CHECK CONSTRAINT [FK_COLOR_TOTIENT_SET_LIBER_COLOR]
GO

ALTER TABLE [dbo].[LIBER_COLOR]  WITH CHECK ADD  CONSTRAINT [FK_LIBER_COLOR_LIBER_PAGE] FOREIGN KEY([LIBER_PAGE_ID])
REFERENCES [dbo].[LIBER_PAGE] ([LIBER_PAGE_ID])
GO

ALTER TABLE [dbo].[LIBER_COLOR] CHECK CONSTRAINT [FK_LIBER_COLOR_LIBER_PAGE]
GO

ALTER TABLE [dbo].[LIBER_COLOR]  WITH CHECK ADD  CONSTRAINT [FK_LIBER_COLOR_LINE_ORIENTATION] FOREIGN KEY([LINE_ORIENTATION_ID])
REFERENCES [dbo].[LINE_ORIENTATION] ([LINE_ORIENTATION_ID])
GO

ALTER TABLE [dbo].[LIBER_COLOR] CHECK CONSTRAINT [FK_LIBER_COLOR_LINE_ORIENTATION]
GO

ALTER TABLE [dbo].[LIBER_COLOR]  WITH CHECK ADD  CONSTRAINT [FK_LIBER_COLOR_PIX_COLOR] FOREIGN KEY([PIX_COLOR_ID])
REFERENCES [dbo].[PIX_COLOR] ([PIX_COLOR_ID])
GO

ALTER TABLE [dbo].[LIBER_COLOR] CHECK CONSTRAINT [FK_LIBER_COLOR_PIX_COLOR]
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO]  WITH CHECK ADD  CONSTRAINT [FK_LINE_COLOR_INFO_LIBER_PAGE] FOREIGN KEY([LIBER_PAGE_ID])
REFERENCES [dbo].[LIBER_PAGE] ([LIBER_PAGE_ID])
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO] CHECK CONSTRAINT [FK_LINE_COLOR_INFO_LIBER_PAGE]
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO]  WITH CHECK ADD  CONSTRAINT [FK_LINE_COLOR_INFO_LINE_ORIENTATION] FOREIGN KEY([LINE_ORIENTATION_ID])
REFERENCES [dbo].[LINE_ORIENTATION] ([LINE_ORIENTATION_ID])
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO] CHECK CONSTRAINT [FK_LINE_COLOR_INFO_LINE_ORIENTATION]
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO]  WITH CHECK ADD  CONSTRAINT [FK_LINE_COLOR_INFO_PIX_COLOR] FOREIGN KEY([PIX_COLOR_ID])
REFERENCES [dbo].[PIX_COLOR] ([PIX_COLOR_ID])
GO

ALTER TABLE [dbo].[LINE_COLOR_INFO] CHECK CONSTRAINT [FK_LINE_COLOR_INFO_PIX_COLOR]
GO

ALTER TABLE [dbo].[PIXEL_POSITION_INFO]  WITH CHECK ADD  CONSTRAINT [FK_PIXEL_POSITION_INFO_LIBER_PAGE] FOREIGN KEY([LIBER_PAGE_ID])
REFERENCES [dbo].[LIBER_PAGE] ([LIBER_PAGE_ID])
GO

ALTER TABLE [dbo].[PIXEL_POSITION_INFO] CHECK CONSTRAINT [FK_PIXEL_POSITION_INFO_LIBER_PAGE]
GO

ALTER TABLE [dbo].[PIXEL_POSITION_INFO]  WITH CHECK ADD  CONSTRAINT [FK_PIXEL_POSITION_INFO_PIX_COLOR] FOREIGN KEY([PIX_COLOR_ID])
REFERENCES [dbo].[PIX_COLOR] ([PIX_COLOR_ID])
GO

ALTER TABLE [dbo].[PIXEL_POSITION_INFO] CHECK CONSTRAINT [FK_PIXEL_POSITION_INFO_PIX_COLOR]
GO

ALTER TABLE [dbo].[TOTIENT_SET]  WITH CHECK ADD  CONSTRAINT [FK_TOTIENT_SET_LINE_COLOR_INFO] FOREIGN KEY([LINE_COLOR_INFO_ID])
REFERENCES [dbo].[LINE_COLOR_INFO] ([LINE_COLOR_INFO_ID])
GO

ALTER TABLE [dbo].[TOTIENT_SET] CHECK CONSTRAINT [FK_TOTIENT_SET_LINE_COLOR_INFO]
GO

USE [LiberPrimus];
GO

IF OBJECT_ID('[dbo].[usp_COLOR_TOTIENT_SETSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_COLOR_TOTIENT_SETSelect] 
END 
GO
CREATE PROC [dbo].[usp_COLOR_TOTIENT_SETSelect] 
    @COLOR_TOTIENT_SET_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [COLOR_TOTIENT_SET_ID], [TOTIENT_NUMBER], [LIBER_COLOR_ID] 
	FROM   [dbo].[COLOR_TOTIENT_SET] 
	WHERE  ([COLOR_TOTIENT_SET_ID] = @COLOR_TOTIENT_SET_ID OR @COLOR_TOTIENT_SET_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_COLOR_TOTIENT_SETInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_COLOR_TOTIENT_SETInsert] 
END 
GO
CREATE PROC [dbo].[usp_COLOR_TOTIENT_SETInsert] 
    @TOTIENT_NUMBER bigint,
    @LIBER_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[COLOR_TOTIENT_SET] ([TOTIENT_NUMBER], [LIBER_COLOR_ID])
	SELECT @TOTIENT_NUMBER, @LIBER_COLOR_ID
	
	-- Begin Return Select <- do not remove
	SELECT [COLOR_TOTIENT_SET_ID], [TOTIENT_NUMBER], [LIBER_COLOR_ID]
	FROM   [dbo].[COLOR_TOTIENT_SET]
	WHERE  [COLOR_TOTIENT_SET_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_COLOR_TOTIENT_SETUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_COLOR_TOTIENT_SETUpdate] 
END 
GO
CREATE PROC [dbo].[usp_COLOR_TOTIENT_SETUpdate] 
    @COLOR_TOTIENT_SET_ID bigint,
    @TOTIENT_NUMBER bigint,
    @LIBER_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[COLOR_TOTIENT_SET]
	SET    [TOTIENT_NUMBER] = @TOTIENT_NUMBER, [LIBER_COLOR_ID] = @LIBER_COLOR_ID
	WHERE  [COLOR_TOTIENT_SET_ID] = @COLOR_TOTIENT_SET_ID
	
	-- Begin Return Select <- do not remove
	SELECT [COLOR_TOTIENT_SET_ID], [TOTIENT_NUMBER], [LIBER_COLOR_ID]
	FROM   [dbo].[COLOR_TOTIENT_SET]
	WHERE  [COLOR_TOTIENT_SET_ID] = @COLOR_TOTIENT_SET_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_COLOR_TOTIENT_SETDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_COLOR_TOTIENT_SETDelete] 
END 
GO
CREATE PROC [dbo].[usp_COLOR_TOTIENT_SETDelete] 
    @COLOR_TOTIENT_SET_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[COLOR_TOTIENT_SET]
	WHERE  [COLOR_TOTIENT_SET_ID] = @COLOR_TOTIENT_SET_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_LIBER_COLORSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_COLORSelect] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_COLORSelect] 
    @LIBER_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [LIBER_COLOR_ID], [LIBER_PAGE_ID], [PIX_COLOR_ID], [LINE_ORIENTATION_ID], [COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE] 
	FROM   [dbo].[LIBER_COLOR] 
	WHERE  ([LIBER_COLOR_ID] = @LIBER_COLOR_ID OR @LIBER_COLOR_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_COLORInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_COLORInsert] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_COLORInsert] 
    @LIBER_PAGE_ID int,
    @PIX_COLOR_ID bigint,
    @LINE_ORIENTATION_ID int,
    @COLOR_COUNT bigint,
    @IS_PRIME bit,
    @GEMETRIA_VALUE nvarchar(5) = NULL,
    @PHI_VALUE bigint = NULL,
    @CHARACTER_VALUE nvarchar(5) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[LIBER_COLOR] ([LIBER_PAGE_ID], [PIX_COLOR_ID], [LINE_ORIENTATION_ID], [COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE])
	SELECT @LIBER_PAGE_ID, @PIX_COLOR_ID, @LINE_ORIENTATION_ID, @COLOR_COUNT, @IS_PRIME, @GEMETRIA_VALUE, @PHI_VALUE, @CHARACTER_VALUE
	
	-- Begin Return Select <- do not remove
	SELECT [LIBER_COLOR_ID], [LIBER_PAGE_ID], [PIX_COLOR_ID], [LINE_ORIENTATION_ID], [COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE]
	FROM   [dbo].[LIBER_COLOR]
	WHERE  [LIBER_COLOR_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_COLORUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_COLORUpdate] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_COLORUpdate] 
    @LIBER_COLOR_ID bigint,
    @LIBER_PAGE_ID int,
    @PIX_COLOR_ID bigint,
    @LINE_ORIENTATION_ID int,
    @COLOR_COUNT bigint,
    @IS_PRIME bit,
    @GEMETRIA_VALUE nvarchar(5) = NULL,
    @PHI_VALUE bigint = NULL,
    @CHARACTER_VALUE nvarchar(5) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[LIBER_COLOR]
	SET    [LIBER_PAGE_ID] = @LIBER_PAGE_ID, [PIX_COLOR_ID] = @PIX_COLOR_ID, [LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID, [COLOR_COUNT] = @COLOR_COUNT, [IS_PRIME] = @IS_PRIME, [GEMETRIA_VALUE] = @GEMETRIA_VALUE, [PHI_VALUE] = @PHI_VALUE, [CHARACTER_VALUE] = @CHARACTER_VALUE
	WHERE  [LIBER_COLOR_ID] = @LIBER_COLOR_ID
	
	-- Begin Return Select <- do not remove
	SELECT [LIBER_COLOR_ID], [LIBER_PAGE_ID], [PIX_COLOR_ID], [LINE_ORIENTATION_ID], [COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE]
	FROM   [dbo].[LIBER_COLOR]
	WHERE  [LIBER_COLOR_ID] = @LIBER_COLOR_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_COLORDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_COLORDelete] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_COLORDelete] 
    @LIBER_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[LIBER_COLOR]
	WHERE  [LIBER_COLOR_ID] = @LIBER_COLOR_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_LIBER_PAGESelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_PAGESelect] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_PAGESelect] 
    @LIBER_PAGE_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [LIBER_PAGE_ID], [LIBER_PAGE_NAME], [LIBER_PAGE_SIG], [LIBER_PAGE_TOTAL_COLORS], [LIBER_PAGE_HEIGHT], [LIBER_PAGE_WIDTH] 
	FROM   [dbo].[LIBER_PAGE] 
	WHERE  ([LIBER_PAGE_ID] = @LIBER_PAGE_ID OR @LIBER_PAGE_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_PAGEInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_PAGEInsert] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_PAGEInsert] 
    @LIBER_PAGE_NAME nvarchar(50),
    @LIBER_PAGE_SIG nvarchar(255),
    @LIBER_PAGE_TOTAL_COLORS int,
    @LIBER_PAGE_HEIGHT int,
    @LIBER_PAGE_WIDTH int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[LIBER_PAGE] ([LIBER_PAGE_NAME], [LIBER_PAGE_SIG], [LIBER_PAGE_TOTAL_COLORS], [LIBER_PAGE_HEIGHT], [LIBER_PAGE_WIDTH])
	SELECT @LIBER_PAGE_NAME, @LIBER_PAGE_SIG, @LIBER_PAGE_TOTAL_COLORS, @LIBER_PAGE_HEIGHT, @LIBER_PAGE_WIDTH
	
	-- Begin Return Select <- do not remove
	SELECT [LIBER_PAGE_ID], [LIBER_PAGE_NAME], [LIBER_PAGE_SIG], [LIBER_PAGE_TOTAL_COLORS], [LIBER_PAGE_HEIGHT], [LIBER_PAGE_WIDTH]
	FROM   [dbo].[LIBER_PAGE]
	WHERE  [LIBER_PAGE_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_PAGEUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_PAGEUpdate] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_PAGEUpdate] 
    @LIBER_PAGE_ID int,
    @LIBER_PAGE_NAME nvarchar(50),
    @LIBER_PAGE_SIG nvarchar(255),
    @LIBER_PAGE_TOTAL_COLORS int,
    @LIBER_PAGE_HEIGHT int,
    @LIBER_PAGE_WIDTH int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[LIBER_PAGE]
	SET    [LIBER_PAGE_NAME] = @LIBER_PAGE_NAME, [LIBER_PAGE_SIG] = @LIBER_PAGE_SIG, [LIBER_PAGE_TOTAL_COLORS] = @LIBER_PAGE_TOTAL_COLORS, [LIBER_PAGE_HEIGHT] = @LIBER_PAGE_HEIGHT, [LIBER_PAGE_WIDTH] = @LIBER_PAGE_WIDTH
	WHERE  [LIBER_PAGE_ID] = @LIBER_PAGE_ID
	
	-- Begin Return Select <- do not remove
	SELECT [LIBER_PAGE_ID], [LIBER_PAGE_NAME], [LIBER_PAGE_SIG], [LIBER_PAGE_TOTAL_COLORS], [LIBER_PAGE_HEIGHT], [LIBER_PAGE_WIDTH]
	FROM   [dbo].[LIBER_PAGE]
	WHERE  [LIBER_PAGE_ID] = @LIBER_PAGE_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LIBER_PAGEDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LIBER_PAGEDelete] 
END 
GO
CREATE PROC [dbo].[usp_LIBER_PAGEDelete] 
    @LIBER_PAGE_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[LIBER_PAGE]
	WHERE  [LIBER_PAGE_ID] = @LIBER_PAGE_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_LINE_COLOR_INFOSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_COLOR_INFOSelect] 
END 
GO
CREATE PROC [dbo].[usp_LINE_COLOR_INFOSelect] 
    @LINE_COLOR_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [LINE_COLOR_INFO_ID], [LINE_NUMBER], [PIX_COLOR_ID], [LIBER_PAGE_ID], [LINE_ORIENTATION_ID], [LINE_COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE] 
	FROM   [dbo].[LINE_COLOR_INFO] 
	WHERE  ([LINE_COLOR_INFO_ID] = @LINE_COLOR_INFO_ID OR @LINE_COLOR_INFO_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_COLOR_INFOInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_COLOR_INFOInsert] 
END 
GO
CREATE PROC [dbo].[usp_LINE_COLOR_INFOInsert] 
    @LINE_NUMBER bigint,
    @PIX_COLOR_ID bigint,
    @LIBER_PAGE_ID int,
    @LINE_ORIENTATION_ID int,
    @LINE_COLOR_COUNT int,
    @IS_PRIME bit,
    @GEMETRIA_VALUE nvarchar(5) = NULL,
    @PHI_VALUE bigint = NULL,
    @CHARACTER_VALUE nvarchar(5) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[LINE_COLOR_INFO] ([LINE_NUMBER], [PIX_COLOR_ID], [LIBER_PAGE_ID], [LINE_ORIENTATION_ID], [LINE_COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE])
	SELECT @LINE_NUMBER, @PIX_COLOR_ID, @LIBER_PAGE_ID, @LINE_ORIENTATION_ID, @LINE_COLOR_COUNT, @IS_PRIME, @GEMETRIA_VALUE, @PHI_VALUE, @CHARACTER_VALUE
	
	-- Begin Return Select <- do not remove
	SELECT [LINE_COLOR_INFO_ID], [LINE_NUMBER], [PIX_COLOR_ID], [LIBER_PAGE_ID], [LINE_ORIENTATION_ID], [LINE_COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE]
	FROM   [dbo].[LINE_COLOR_INFO]
	WHERE  [LINE_COLOR_INFO_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_COLOR_INFOUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_COLOR_INFOUpdate] 
END 
GO
CREATE PROC [dbo].[usp_LINE_COLOR_INFOUpdate] 
    @LINE_COLOR_INFO_ID bigint,
    @LINE_NUMBER bigint,
    @PIX_COLOR_ID bigint,
    @LIBER_PAGE_ID int,
    @LINE_ORIENTATION_ID int,
    @LINE_COLOR_COUNT int,
    @IS_PRIME bit,
    @GEMETRIA_VALUE nvarchar(5) = NULL,
    @PHI_VALUE bigint = NULL,
    @CHARACTER_VALUE nvarchar(5) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[LINE_COLOR_INFO]
	SET    [LINE_NUMBER] = @LINE_NUMBER, [PIX_COLOR_ID] = @PIX_COLOR_ID, [LIBER_PAGE_ID] = @LIBER_PAGE_ID, [LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID, [LINE_COLOR_COUNT] = @LINE_COLOR_COUNT, [IS_PRIME] = @IS_PRIME, [GEMETRIA_VALUE] = @GEMETRIA_VALUE, [PHI_VALUE] = @PHI_VALUE, [CHARACTER_VALUE] = @CHARACTER_VALUE
	WHERE  [LINE_COLOR_INFO_ID] = @LINE_COLOR_INFO_ID
	
	-- Begin Return Select <- do not remove
	SELECT [LINE_COLOR_INFO_ID], [LINE_NUMBER], [PIX_COLOR_ID], [LIBER_PAGE_ID], [LINE_ORIENTATION_ID], [LINE_COLOR_COUNT], [IS_PRIME], [GEMETRIA_VALUE], [PHI_VALUE], [CHARACTER_VALUE]
	FROM   [dbo].[LINE_COLOR_INFO]
	WHERE  [LINE_COLOR_INFO_ID] = @LINE_COLOR_INFO_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_COLOR_INFODelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_COLOR_INFODelete] 
END 
GO
CREATE PROC [dbo].[usp_LINE_COLOR_INFODelete] 
    @LINE_COLOR_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[LINE_COLOR_INFO]
	WHERE  [LINE_COLOR_INFO_ID] = @LINE_COLOR_INFO_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_LINE_ORIENTATIONSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_ORIENTATIONSelect] 
END 
GO
CREATE PROC [dbo].[usp_LINE_ORIENTATIONSelect] 
    @LINE_ORIENTATION_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [LINE_ORIENTATION_ID], [LINE_ORIENTATION_NAME] 
	FROM   [dbo].[LINE_ORIENTATION] 
	WHERE  ([LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID OR @LINE_ORIENTATION_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_ORIENTATIONInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_ORIENTATIONInsert] 
END 
GO
CREATE PROC [dbo].[usp_LINE_ORIENTATIONInsert] 
    @LINE_ORIENTATION_NAME nvarchar(50)
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[LINE_ORIENTATION] ([LINE_ORIENTATION_NAME])
	SELECT @LINE_ORIENTATION_NAME
	
	-- Begin Return Select <- do not remove
	SELECT [LINE_ORIENTATION_ID], [LINE_ORIENTATION_NAME]
	FROM   [dbo].[LINE_ORIENTATION]
	WHERE  [LINE_ORIENTATION_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_ORIENTATIONUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_ORIENTATIONUpdate] 
END 
GO
CREATE PROC [dbo].[usp_LINE_ORIENTATIONUpdate] 
    @LINE_ORIENTATION_ID int,
    @LINE_ORIENTATION_NAME nvarchar(50)
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[LINE_ORIENTATION]
	SET    [LINE_ORIENTATION_NAME] = @LINE_ORIENTATION_NAME
	WHERE  [LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID
	
	-- Begin Return Select <- do not remove
	SELECT [LINE_ORIENTATION_ID], [LINE_ORIENTATION_NAME]
	FROM   [dbo].[LINE_ORIENTATION]
	WHERE  [LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_LINE_ORIENTATIONDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_LINE_ORIENTATIONDelete] 
END 
GO
CREATE PROC [dbo].[usp_LINE_ORIENTATIONDelete] 
    @LINE_ORIENTATION_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[LINE_ORIENTATION]
	WHERE  [LINE_ORIENTATION_ID] = @LINE_ORIENTATION_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_PIX_COLORSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIX_COLORSelect] 
END 
GO
CREATE PROC [dbo].[usp_PIX_COLORSelect] 
    @PIX_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [PIX_COLOR_ID], [PIX_COLOR_VALUE] 
	FROM   [dbo].[PIX_COLOR] 
	WHERE  ([PIX_COLOR_ID] = @PIX_COLOR_ID OR @PIX_COLOR_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIX_COLORInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIX_COLORInsert] 
END 
GO
CREATE PROC [dbo].[usp_PIX_COLORInsert] 
    @PIX_COLOR_VALUE nvarchar(10) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[PIX_COLOR] ([PIX_COLOR_VALUE])
	SELECT @PIX_COLOR_VALUE
	
	-- Begin Return Select <- do not remove
	SELECT [PIX_COLOR_ID], [PIX_COLOR_VALUE]
	FROM   [dbo].[PIX_COLOR]
	WHERE  [PIX_COLOR_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIX_COLORUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIX_COLORUpdate] 
END 
GO
CREATE PROC [dbo].[usp_PIX_COLORUpdate] 
    @PIX_COLOR_ID bigint,
    @PIX_COLOR_VALUE nvarchar(10) = NULL
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[PIX_COLOR]
	SET    [PIX_COLOR_VALUE] = @PIX_COLOR_VALUE
	WHERE  [PIX_COLOR_ID] = @PIX_COLOR_ID
	
	-- Begin Return Select <- do not remove
	SELECT [PIX_COLOR_ID], [PIX_COLOR_VALUE]
	FROM   [dbo].[PIX_COLOR]
	WHERE  [PIX_COLOR_ID] = @PIX_COLOR_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIX_COLORDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIX_COLORDelete] 
END 
GO
CREATE PROC [dbo].[usp_PIX_COLORDelete] 
    @PIX_COLOR_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[PIX_COLOR]
	WHERE  [PIX_COLOR_ID] = @PIX_COLOR_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_PIXEL_POSITION_INFOSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIXEL_POSITION_INFOSelect] 
END 
GO
CREATE PROC [dbo].[usp_PIXEL_POSITION_INFOSelect] 
    @PIXEL_POSITION_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [PIXEL_POSITION_INFO_ID], [PIXEL_POSITION_X], [PIXEL_POSITION_Y], [PIXEL_POSITION_CHANNELS], [PIX_COLOR_ID], [LIBER_PAGE_ID] 
	FROM   [dbo].[PIXEL_POSITION_INFO] 
	WHERE  ([PIXEL_POSITION_INFO_ID] = @PIXEL_POSITION_INFO_ID OR @PIXEL_POSITION_INFO_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIXEL_POSITION_INFOInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIXEL_POSITION_INFOInsert] 
END 
GO
CREATE PROC [dbo].[usp_PIXEL_POSITION_INFOInsert] 
    @PIXEL_POSITION_X bigint,
    @PIXEL_POSITION_Y bigint,
    @PIXEL_POSITION_CHANNELS int,
    @PIX_COLOR_ID bigint,
    @LIBER_PAGE_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[PIXEL_POSITION_INFO] ([PIXEL_POSITION_X], [PIXEL_POSITION_Y], [PIXEL_POSITION_CHANNELS], [PIX_COLOR_ID], [LIBER_PAGE_ID])
	SELECT @PIXEL_POSITION_X, @PIXEL_POSITION_Y, @PIXEL_POSITION_CHANNELS, @PIX_COLOR_ID, @LIBER_PAGE_ID
	
	-- Begin Return Select <- do not remove
	SELECT [PIXEL_POSITION_INFO_ID], [PIXEL_POSITION_X], [PIXEL_POSITION_Y], [PIXEL_POSITION_CHANNELS], [PIX_COLOR_ID], [LIBER_PAGE_ID]
	FROM   [dbo].[PIXEL_POSITION_INFO]
	WHERE  [PIXEL_POSITION_INFO_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIXEL_POSITION_INFOUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIXEL_POSITION_INFOUpdate] 
END 
GO
CREATE PROC [dbo].[usp_PIXEL_POSITION_INFOUpdate] 
    @PIXEL_POSITION_INFO_ID bigint,
    @PIXEL_POSITION_X bigint,
    @PIXEL_POSITION_Y bigint,
    @PIXEL_POSITION_CHANNELS int,
    @PIX_COLOR_ID bigint,
    @LIBER_PAGE_ID int
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[PIXEL_POSITION_INFO]
	SET    [PIXEL_POSITION_X] = @PIXEL_POSITION_X, [PIXEL_POSITION_Y] = @PIXEL_POSITION_Y, [PIXEL_POSITION_CHANNELS] = @PIXEL_POSITION_CHANNELS, [PIX_COLOR_ID] = @PIX_COLOR_ID, [LIBER_PAGE_ID] = @LIBER_PAGE_ID
	WHERE  [PIXEL_POSITION_INFO_ID] = @PIXEL_POSITION_INFO_ID
	
	-- Begin Return Select <- do not remove
	SELECT [PIXEL_POSITION_INFO_ID], [PIXEL_POSITION_X], [PIXEL_POSITION_Y], [PIXEL_POSITION_CHANNELS], [PIX_COLOR_ID], [LIBER_PAGE_ID]
	FROM   [dbo].[PIXEL_POSITION_INFO]
	WHERE  [PIXEL_POSITION_INFO_ID] = @PIXEL_POSITION_INFO_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_PIXEL_POSITION_INFODelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_PIXEL_POSITION_INFODelete] 
END 
GO
CREATE PROC [dbo].[usp_PIXEL_POSITION_INFODelete] 
    @PIXEL_POSITION_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[PIXEL_POSITION_INFO]
	WHERE  [PIXEL_POSITION_INFO_ID] = @PIXEL_POSITION_INFO_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

IF OBJECT_ID('[dbo].[usp_TOTIENT_SETSelect]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_TOTIENT_SETSelect] 
END 
GO
CREATE PROC [dbo].[usp_TOTIENT_SETSelect] 
    @TOTIENT_SET_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  

	BEGIN TRAN

	SELECT [TOTIENT_SET_ID], [TOTIENT_NUMBER], [LINE_COLOR_INFO_ID] 
	FROM   [dbo].[TOTIENT_SET] 
	WHERE  ([TOTIENT_SET_ID] = @TOTIENT_SET_ID OR @TOTIENT_SET_ID IS NULL) 

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_TOTIENT_SETInsert]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_TOTIENT_SETInsert] 
END 
GO
CREATE PROC [dbo].[usp_TOTIENT_SETInsert] 
    @TOTIENT_NUMBER bigint,
    @LINE_COLOR_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN
	
	INSERT INTO [dbo].[TOTIENT_SET] ([TOTIENT_NUMBER], [LINE_COLOR_INFO_ID])
	SELECT @TOTIENT_NUMBER, @LINE_COLOR_INFO_ID
	
	-- Begin Return Select <- do not remove
	SELECT [TOTIENT_SET_ID], [TOTIENT_NUMBER], [LINE_COLOR_INFO_ID]
	FROM   [dbo].[TOTIENT_SET]
	WHERE  [TOTIENT_SET_ID] = SCOPE_IDENTITY()
	-- End Return Select <- do not remove
               
	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_TOTIENT_SETUpdate]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_TOTIENT_SETUpdate] 
END 
GO
CREATE PROC [dbo].[usp_TOTIENT_SETUpdate] 
    @TOTIENT_SET_ID bigint,
    @TOTIENT_NUMBER bigint,
    @LINE_COLOR_INFO_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	UPDATE [dbo].[TOTIENT_SET]
	SET    [TOTIENT_NUMBER] = @TOTIENT_NUMBER, [LINE_COLOR_INFO_ID] = @LINE_COLOR_INFO_ID
	WHERE  [TOTIENT_SET_ID] = @TOTIENT_SET_ID
	
	-- Begin Return Select <- do not remove
	SELECT [TOTIENT_SET_ID], [TOTIENT_NUMBER], [LINE_COLOR_INFO_ID]
	FROM   [dbo].[TOTIENT_SET]
	WHERE  [TOTIENT_SET_ID] = @TOTIENT_SET_ID	
	-- End Return Select <- do not remove

	COMMIT
GO
IF OBJECT_ID('[dbo].[usp_TOTIENT_SETDelete]') IS NOT NULL
BEGIN 
    DROP PROC [dbo].[usp_TOTIENT_SETDelete] 
END 
GO
CREATE PROC [dbo].[usp_TOTIENT_SETDelete] 
    @TOTIENT_SET_ID bigint
AS 
	SET NOCOUNT ON 
	SET XACT_ABORT ON  
	
	BEGIN TRAN

	DELETE
	FROM   [dbo].[TOTIENT_SET]
	WHERE  [TOTIENT_SET_ID] = @TOTIENT_SET_ID

	COMMIT
GO
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

USE [LiberPrimus]
GO

/****** Object:  Table [dbo].[CODE_SET_TABLES]    Script Date: 3/9/2024 4:02:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CODE_SET_TABLES](
	[CODE_SET_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE_SET_NAME] [nvarchar](50) NOT NULL,
	[CODE_SET_CHARACTER] [nvarchar](10) NOT NULL,
	[CODE_SET_DECIMAL] [bigint] NOT NULL,
	[CODE_SET_BINARY_STRING] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_CODE_SET_TABLES] PRIMARY KEY CLUSTERED 
(
	[CODE_SET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [LiberPrimus]
GO

INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<NUL>',0, '0000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<SOH>',1,'0000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<STX>',2,'0000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<ETX>',3,'0000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<EOT>',4,'0000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<ENQ>',5,'0000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<ACK>',6,'0000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<BEL>',7,'0000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<BS>',8,'0001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<HT>',9,'0001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<LF>',10,'0001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<VT>',11,'0001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<FF>',12,'0001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<CR>',13,'0001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<SO>',14,'0001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<SI>',15,'0001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DLE>',16,'0010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DC1>',17,'0010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DC2>',18,'0010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DC3>',19,'0010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DC4>',20,'0010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<NAK>',21,'0010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<SYN>',22,'0010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<ETB>',23,'0010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<CAN>',24,'0011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<EM>',25,'0011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<SUB>',26,'0011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<ESC>',27,'0011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<FS>',28,'0011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<GS>',29,'0011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<RS>',30,'0011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<US>',31,'0011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',' ',32,'0100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','!',33,'0100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','"',34,'0100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','#',35,'0100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','$',36,'0100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','%',37,'0100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','&',38,'0100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','',39,'0100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','(',40,'0101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',')',41,'0101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','*',42,'0101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','+',43,'0101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',',',44,'0101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','-',45,'0101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','.',46,'0101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','/',47,'0101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','0',48,'0110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','1',49,'0110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','2',50,'0110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','3',51,'0110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','4',52,'0110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','5',53,'0110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','6',54,'0110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','7',55,'0110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','8',56,'0111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','9',57,'0111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',':',58,'0111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',';',59,'0111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<',60,'0111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','=',61,'0111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','>',62,'0111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','?',63,'0111111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','@',64,'1000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','A',65,'1000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','B',66,'1000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','C',67,'1000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','D',68,'1000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','E',69,'1000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','F',70,'1000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','G',71,'1000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','H',72,'1001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','I',73,'1001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','J',74,'1001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','K',75,'1001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','L',76,'1001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','M',77,'1001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','N',78,'1001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','O',79,'1001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','P',80,'1010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','Q',81,'1010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','R',82,'1010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','S',83,'1010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','T',84,'1010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','U',85,'1010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','V',86,'1010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','W',87,'1010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','X',88,'1011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','Y',89,'1011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','Z',90,'1011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','[',91,'1011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','\',92,'1011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII',']',93,'1011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','^',94,'1011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','_',95,'1011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','`',96,'1100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','a',97,'1100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','b',98,'1100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','c',99,'1100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','d',100,'1100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','e',101,'1100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','f',102,'1100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','g',103,'1100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','h',104,'1101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','i',105,'1101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','j',106,'1101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','k',107,'1101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','l',108,'1101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','m',109,'1101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','n',110,'1101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','o',111,'1101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','p',112,'1110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','q',113,'1110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','r',114,'1110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','s',115,'1110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','t',116,'1110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','u',117,'1110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','v',118,'1110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','w',119,'1110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','x',120,'1111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','y',121,'1111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','z',122,'1111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','{',123,'1111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','|',124,'1111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','}',125,'1111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','~',126,'1111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ASCII','<DEL>',127,'1111111')

GO

USE [LiberPrimus]
GO

INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<NUL>',0, '00000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<SOH>',1,'00000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<STX>',2,'00000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<ETX>',3,'00000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<EOT>',4,'00000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<ENQ>',5,'00000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<ACK>',6,'00000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<BEL>',7,'00000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<BS>',8,'00001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<HT>',9,'00001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<LF>',10,'00001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<VT>',11,'00001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<FF>',12,'00001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<CR>',13,'00001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<SO>',14,'00001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<SI>',15,'00001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DLE>',16,'00010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DC1>',17,'00010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DC2>',18,'00010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DC3>',19,'00010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DC4>',20,'00010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<NAK>',21,'00010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<SYN>',22,'00010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<ETB>',23,'00010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<CAN>',24,'00011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<EM>',25,'00011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<SUB>',26,'00011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<ESC>',27,'00011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<FS>',28,'00011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<GS>',29,'00011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<RS>',30,'00011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<US>',31,'00011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',' ',32,'00100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','!',33,'00100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','"',34,'00100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','#',35,'00100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','$',36,'00100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','%',37,'00100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','&',38,'00100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',39,'00100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','(',40,'00101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',')',41,'00101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','*',42,'00101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','+',43,'00101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',',',44,'00101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','-',45,'00101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','.',46,'00101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','/',47,'00101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','0',48,'00110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','1',49,'00110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','2',50,'00110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','3',51,'00110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','4',52,'00110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','5',53,'00110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','6',54,'00110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','7',55,'00110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','8',56,'00111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','9',57,'00111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',':',58,'00111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',';',59,'00111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<',60,'00111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','=',61,'00111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','>',62,'00111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','?',63,'00111111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','@',64,'01000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','A',65,'01000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','B',66,'01000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','C',67,'01000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','D',68,'01000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','E',69,'01000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','F',70,'01000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','G',71,'01000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','H',72,'01001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','I',73,'01001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','J',74,'01001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','K',75,'01001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','L',76,'01001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','M',77,'01001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','N',78,'01001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','O',79,'01001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','P',80,'01010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Q',81,'01010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','R',82,'01010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','S',83,'01010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','T',84,'01010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','U',85,'01010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','V',86,'01010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','W',87,'01010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','X',88,'01011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Y',89,'01011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Z',90,'01011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','[',91,'01011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','\',92,'01011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI',']',93,'01011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','^',94,'01011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','_',95,'01011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','`',96,'01100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','a',97,'01100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','b',98,'01100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','c',99,'01100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','d',100,'01100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','e',101,'01100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','f',102,'01100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','g',103,'01100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','h',104,'01101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','i',105,'01101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','j',106,'01101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','k',107,'01101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','l',108,'01101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','m',109,'01101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','n',110,'01101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','o',111,'01101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','p',112,'01110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','q',113,'01110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','r',114,'01110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','s',115,'01110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','t',116,'01110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','u',117,'01110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','v',118,'01110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','w',119,'01110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','x',120,'01111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','y',121,'01111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','z',122,'01111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','{',123,'01111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','|',124,'01111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','}',125,'01111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','~',126,'01111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','<DEL>',127,'01111111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','€',128,'10000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',129,'10000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','‚',130,'10000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ƒ',131,'10000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','„',132,'10000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','…',133,'10000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','†',134,'10000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','‡',135,'10000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ˆ',136,'10001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','‰',137,'10001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Š',138,'10001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','‹',139,'10001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Œ',140,'10001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',141,'10001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ž',142,'10001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',143,'10001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',144,'10010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','‘',145,'10010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','’',146,'10010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','“',147,'10010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','”',148,'10010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','•',149,'10010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','–',150,'10010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','—',151,'10010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','˜',152,'10011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','™',153,'10011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','š',154,'10011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','›',155,'10011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','œ',156,'10011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','', 157,'10011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ž',158,'10011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ÿ',159,'10011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','',160,'10100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¡',161,'10100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¢',162,'10100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','£',163,'10100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¤',164,'10100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¥',165,'10100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¦',166,'10100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','§',167,'10100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¨',168,'10101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','©',169,'10101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ª',170,'10101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','«',171,'10101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¬',172,'10101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','­',173,'10101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','®',174,'10101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¯',175,'10101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','°',176,'10110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','±',177,'10110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','²',178,'10110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','³',179,'10110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','´',180,'10110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','µ',181,'10110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¶',182,'10110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','·',183,'10110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¸',184,'10111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¹',185,'10111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','º',186,'10111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','»',187,'10111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¼',188,'10111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','½',189,'10111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¾',190,'10111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','¿',191,'10111111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','À',192,'11000000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Á',193,'11000001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Â',194,'11000010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ã',195,'11000011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ä',196,'11000100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Å',197,'11000101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Æ',198,'11000110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ç',199,'11000111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','È',200,'11001000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','É',201,'11001001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ê',202,'11001010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ë',203,'11001011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ì',204,'11001100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Í',205,'11001101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Î',206,'11001110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ï',207,'11001111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ð',208,'11010000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ñ',209,'11010001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ò',210,'11010010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ó',211,'11010011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ô',212,'11010100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Õ',213,'11010101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ö',214,'11010110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','×',215,'11010111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ø',216,'11011000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ù',217,'11011001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ú',218,'11011010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Û',219,'11011011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ü',220,'11011100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Ý',221,'11011101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','Þ',222,'11011110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ß',223,'11011111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','à',224,'11100000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','á',225,'11100001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','â',226,'11100010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ã',227,'11100011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ä',228,'11100100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','å',229,'11100101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','æ',230,'11100110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ç',231,'11100111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','è',232,'11101000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','é',233,'11101001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ê',234,'11101010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ë',235,'11101011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ì',236,'11101100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','í',237,'11101101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','î',238,'11101110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ï',239,'11101111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ð',240,'11110000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ñ',241,'11110001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ò',242,'11110010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ó',243,'11110011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ô',244,'11110100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','õ',245,'11110101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ö',246,'11110110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','÷',247,'11110111')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ø',248,'11111000')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ù',249,'11111001')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ú',250,'11111010')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','û',251,'11111011')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ü',252,'11111100')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ý',253,'11111101')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','þ',254,'11111110')
INSERT INTO [dbo].[CODE_SET_TABLES]([CODE_SET_NAME],[CODE_SET_CHARACTER],[CODE_SET_DECIMAL],[CODE_SET_BINARY_STRING])VALUES('ANSI','ÿ',255,'11111111')

GO